// backend/taxonomy.js — Insight Vault

const PILLARS = [
  {
    id: 'P1', name_en: 'Personal Development & Effectiveness', name_pt: 'Desenvolvimento Pessoal & Eficácia',
    topics: [
      { id: 'P1.01', name: 'Desenvolvimento' },
      { id: 'P1.02', name: 'Desenvolvimento pessoal' },
      { id: 'P1.03', name: 'Melhoria contínua' },
      { id: 'P1.04', name: 'Lifelong learning' },
      { id: 'P1.05', name: 'Aprendizagem' },
      { id: 'P1.06', name: 'Conhecimento' },
      { id: 'P1.07', name: 'Proatividade' },
      { id: 'P1.08', name: 'Eficácia' },
      { id: 'P1.09', name: 'Eficiência' },
      { id: 'P1.10', name: 'Gestão de tempo' },
      { id: 'P1.11', name: 'Time management' },
      { id: 'P1.12', name: 'Disciplina' },
      { id: 'P1.13', name: 'Hábitos' },
      { id: 'P1.14', name: 'Excelência' },
      { id: 'P1.15', name: 'Organização' },
      { id: 'P1.16', name: 'Foco' },
      { id: 'P1.17', name: 'Deep work' },
      { id: 'P1.18', name: 'Resiliência' },
      { id: 'P1.19', name: 'Grit' },
      { id: 'P1.20', name: 'Persistência' },
      { id: 'P1.21', name: 'Perseverança' },
      { id: 'P1.22', name: 'Consistência' },
      { id: 'P1.23', name: 'Mentalidade de crescimento' },
      { id: 'P1.24', name: 'Growth Mindset' },
      { id: 'P1.25', name: 'Crescimento' },
      { id: 'P1.26', name: 'Performance' },
      { id: 'P1.27', name: 'Pensamento crítico' },
      { id: 'P1.28', name: 'Método científico' },
    ],
  },
  {
    id: 'P2', name_en: 'Health, Wellbeing & Spirituality', name_pt: 'Saúde, Bem-estar & Espiritualidade',
    topics: [
      { id: 'P2.01', name: 'Equilíbrio' },
      { id: 'P2.02', name: 'Saúde física' },
      { id: 'P2.03', name: 'Ginástica e treinos' },
      { id: 'P2.04', name: 'Nutrição & suplementação' },
      { id: 'P2.05', name: 'Sono' },
      { id: 'P2.06', name: 'Saúde mental' },
      { id: 'P2.07', name: 'Terapia' },
      { id: 'P2.08', name: 'Inteligência Emocional' },
      { id: 'P2.09', name: 'Autoconhecimento' },
      { id: 'P2.10', name: 'Lazer' },
      { id: 'P2.11', name: 'Hobbies' },
      { id: 'P2.12', name: 'Bem-estar' },
      { id: 'P2.13', name: 'Espiritualidade & religião' },
      { id: 'P2.14', name: 'Gestão de estresse' },
      { id: 'P2.15', name: 'Energia' },
      { id: 'P2.16', name: 'Vitalidade' },
      { id: 'P2.17', name: 'Longevidade' },
      { id: 'P2.18', name: 'Conexão' },
      { id: 'P2.19', name: 'Meditação' },
      { id: 'P2.20', name: 'Paz interior' },
      { id: 'P2.21', name: 'Escuta do coração' },
      { id: 'P2.22', name: 'Transcendência' },
      { id: 'P2.23', name: 'Consciência' },
      { id: 'P2.24', name: 'Propósito' },
      { id: 'P2.25', name: 'Sentido' },
      { id: 'P2.26', name: 'Felicidade' },
      { id: 'P2.27', name: 'Happiness' },
      { id: 'P2.28', name: 'Gratidão' },
      { id: 'P2.29', name: 'Humanidade' },
      { id: 'P2.30', name: 'Otimismo' },
      { id: 'P2.31', name: 'Vulnerabilidade' },
      { id: 'P2.32', name: 'Sabedoria' },
      { id: 'P2.33', name: 'Realização' },
    ],
  },
  {
    id: 'P3', name_en: 'Attitude & Image', name_pt: 'Atitude & Imagem',
    topics: [
      { id: 'P3.01', name: 'Atitude' },
      { id: 'P3.02', name: 'Postura' },
      { id: 'P3.03', name: 'Postura profissional' },
      { id: 'P3.04', name: 'Imagem' },
      { id: 'P3.05', name: 'Imagem pública' },
      { id: 'P3.06', name: 'Mídias sociais' },
      { id: 'P3.07', name: 'Reputação' },
      { id: 'P3.08', name: 'Vestuário' },
      { id: 'P3.09', name: 'Marca pessoal' },
      { id: 'P3.10', name: 'Identidade' },
      { id: 'P3.11', name: 'Autenticidade' },
      { id: 'P3.12', name: 'Inovação' },
      { id: 'P3.13', name: 'Flexibilidade' },
      { id: 'P3.14', name: 'Criatividade' },
    ],
  },
  {
    id: 'P4', name_en: 'Relationships, Communication & Sales', name_pt: 'Relacionamentos, Comunicação & Vendas',
    topics: [
      { id: 'P4.01', name: 'Relacionamentos' },
      { id: 'P4.02', name: 'Amizades' },
      { id: 'P4.03', name: 'Comunidades' },
      { id: 'P4.04', name: 'Networking' },
      { id: 'P4.05', name: 'Comunicação' },
      { id: 'P4.06', name: 'Comunicação não violenta' },
      { id: 'P4.07', name: 'Escuta' },
      { id: 'P4.08', name: 'Escuta ativa' },
      { id: 'P4.09', name: 'Empatia' },
      { id: 'P4.10', name: 'Rapport' },
      { id: 'P4.11', name: 'Oratória' },
      { id: 'P4.12', name: 'Influência' },
      { id: 'P4.13', name: 'Persuasão' },
      { id: 'P4.14', name: 'Negociação' },
      { id: 'P4.15', name: 'Resolução de conflitos' },
      { id: 'P4.16', name: 'Vendas' },
      { id: 'P4.17', name: 'Storytelling' },
    ],
  },
  {
    id: 'P5', name_en: 'Leadership, Strategy & Culture', name_pt: 'Liderança, Estratégia & Cultura',
    topics: [
      { id: 'P5.01', name: 'Liderança' },
      { id: 'P5.02', name: 'Gestão de pessoas' },
      { id: 'P5.03', name: 'Gestão de projetos' },
      { id: 'P5.04', name: 'Scrum' },
      { id: 'P5.05', name: 'Trabalho em equipe' },
      { id: 'P5.06', name: 'Delegação' },
      { id: 'P5.07', name: 'Cultura' },
      { id: 'P5.08', name: 'Cultura de Excelência' },
      { id: 'P5.09', name: 'Missão Visão e Valores Organizacionais' },
      { id: 'P5.10', name: 'Estratégia' },
      { id: 'P5.11', name: 'Estratégia empresarial' },
      { id: 'P5.12', name: 'Governança' },
      { id: 'P5.13', name: 'Sistemas organizacionais' },
      { id: 'P5.14', name: 'Decisão' },
      { id: 'P5.15', name: 'Decision making' },
    ],
  },
  {
    id: 'P6', name_en: 'Business, Money & Wealth', name_pt: 'Negócios, Dinheiro & Riqueza',
    topics: [
      { id: 'P6.01', name: 'Finanças' },
      { id: 'P6.02', name: 'Dinheiro' },
      { id: 'P6.03', name: 'Patrimônio' },
      { id: 'P6.04', name: 'Ativos' },
      { id: 'P6.05', name: 'Gestão financeira' },
      { id: 'P6.06', name: 'Alocação de capital' },
      { id: 'P6.07', name: 'Investimentos' },
      { id: 'P6.08', name: 'Avaliação de risco' },
      { id: 'P6.09', name: 'Empreendedorismo' },
    ],
  },
  {
    id: 'P7', name_en: 'Values, Character & Integrity', name_pt: 'Valores, Caráter & Integridade',
    topics: [
      { id: 'P7.01', name: 'Ética' },
      { id: 'P7.02', name: 'Justiça' },
      { id: 'P7.03', name: 'Moral' },
      { id: 'P7.04', name: 'Responsabilidade' },
      { id: 'P7.05', name: 'Seriedade' },
      { id: 'P7.06', name: 'Compromisso' },
      { id: 'P7.07', name: 'Honra' },
      { id: 'P7.08', name: 'Integridade' },
      { id: 'P7.09', name: 'Coragem' },
      { id: 'P7.10', name: 'Coragem Moral' },
      { id: 'P7.11', name: 'Caráter' },
      { id: 'P7.12', name: 'Virtude' },
      { id: 'P7.13', name: 'Compaixão' },
      { id: 'P7.14', name: 'Humildade' },
      { id: 'P7.15', name: 'Liberdade' },
      { id: 'P7.16', name: 'Princípios' },
      { id: 'P7.17', name: 'Valores' },
      { id: 'P7.18', name: 'Serviço' },
    ],
  },
  {
    id: 'P8', name_en: 'Family & Legacy', name_pt: 'Família & Legado',
    topics: [
      { id: 'P8.01', name: 'Família' },
      { id: 'P8.02', name: 'Legado' },
      { id: 'P8.03', name: 'Nome' },
      { id: 'P8.04', name: 'Reputação' },
      { id: 'P8.05', name: 'Paternidade' },
      { id: 'P8.06', name: 'Presença emocional' },
      { id: 'P8.07', name: 'Tradições familiares' },
      { id: 'P8.08', name: 'Modelo de vida' },
      { id: 'P8.09', name: 'Educação moral' },
      { id: 'P8.10', name: 'Experiências' },
      { id: 'P8.11', name: 'Cartas e orientações' },
    ],
  },
];

module.exports = { PILLARS };
